### ISSUE TITLE
Add @x-state/fsm XState comparison in the wiki

### ISSUE THREAD

**Issue by ibrahimcesar** [cassiozen/useStateMachine#27]
Hi,

First great work! Can't wait to start use this on my projects from now on.

I just want to suggest, if you find suitable, that in the wiki page in comparison with XState, that if for some reason people are looking for a minimal implementation of XState for another use-cases that are not React (lambda is one I could think on the top of mind), they can use [@xstate/fsm](https://xstate.js.org/docs/packages/xstate-fsm).

Thanks and again congrats on the great work!

**Comment by cassiozen** [comment]
Thanks. 

The gist is: 

- Right now both libs are similar in feature set - but this might change in the future as we're currently working on hierarchical state machines support.
- They're both small, so if size is your main consideration you can't go wrong with any.
- Pros: This is more react idiomatic, and has a great TypeScript support with automatic type inference.

Looking for help to structure this in a small piece of text we could put on the wiki. Any volunteers? @ibrahimcesar, @mtsknn, @tangdw.
