### ISSUE TITLE
DX for typed events

### ISSUE THREAD

**Issue by cassiozen** [cassiozen/useStateMachine#65]
Hey @devanshj, when using types events, I'm getting a confusing error message. Here's a sample case:

1 - I have a types "UPDATE" event that requires a string value
2 - When trying `send({ type: "UPDATE" })` it gives me an error (right, it is missing the `value`)
3 - Problem is, the error says `Type '"UPDATE"' is not assignable to type '"some other type"'`:

Here is an example (the `examples/form` with this added send on line 57:
<img width="945" alt="Screen Shot 2021-07-28 at 9 49 43 AM" src="https://user-images.githubusercontent.com/33676/127344890-e3af0e05-848b-4405-bb0d-b2b6a28325ca.png">

**Comment by cassiozen** [comment]
I understand that TypeScript is showing one example of a correct possible value - but since you apparently can bend TypeScript to your will 🤪, can anything be done here?

**Comment by devanshj** [comment]
> you apparently can bend TypeScript to your will 🤪

HAHAHAHA this is 100% going to twitter xD

Could you send that code? I can't repro minimally.

**Comment by devanshj** [comment]
This is most probably a bug, so i'll report it to typescript team, meanwhile let me see if I can send a workaround

**Comment by devanshj** [comment]
The repro is simpler than I thought xD I was guessing it takes time to compute hence typescript was showing bad errors

![image](https://user-images.githubusercontent.com/30295578/127353620-60d9a7a3-2743-412e-b2d2-d139d46dad15.png)

**Comment by cassiozen** [comment]
> you apparently can bend TypeScript to your will 

Stands true ;)

**Comment by cassiozen** [comment]
> sending a PR

I'll publish the beta after we merge this then.

**Comment by devanshj** [comment]
For reference and reminder to revert overloads when [#45217](https://github.com/microsoft/TypeScript/issues/45217) gets fixed.
